# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
 vmImage: 'ubuntu-20.04'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarFrontend'
        organization: '410994'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '410994_ReactKwitter'
        cliProjectName: 'ReactKwitter'
        cliSources: '.'
    - task: Npm@1
      inputs:
       command: 'custom'
       customCommand: 'run build'

    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerPersonalProject'
        command: 'login'
        addPipelineData: false
   
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerPersonalProject'
        repository: '22021999/reactkwitter'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 'latest'
        addPipelineData: false
    
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerPersonalProject'
        command: 'logout'
        addPipelineData: false
      